/*jshint esversion: 6 */
const web = [
    "truyentranhaudio.online",
    "truyentranhaudio.com",
    "vcomic.net",
    "nettruyentop.com",
    "nhattruyentranh.com",
    "truyenchon.com",
    "mangatx.com",
    "mangakakalot.com",
    "manganelo.com",
    "readmanganato.com",
    "www.a3manga.com",
    "www.ngonphong.com",
    "shieldmanga.club",
    "truyensieuhay.com",
    "truyenz.info",
    "mangafoxfull.com",
    "www.webtoon.xyz",
    "www.webtoons.com",
    "h5.mangatoon.mobi",
    "tienycomic.xyz",
    "truyenqq.com",
    "saytruyen.net",
    "beeng.net",
    "wcomic.net",
    "vlogtruyen.com",
    "cmanga.com"
];
// 19
