/*jshint esversion: 6 */
const web = [
    "doctruyen3q",
    "toptruyen",
    "truyentranhaudio",
    "vcomic",
    "vcomi",
    "nettruyen",
    "nhattruyen",
    "truyenchon",
    "mangatx",
    "mangakakalot",
    "manganelo",
    "readmanganato",
    "www.a3mnga",
    "www.ngonphong",
    "shieldmanga",
    "truyensieuhay",
    "truyenz.info",
    "mangafoxfull",
    "www.webtoon",
    "www.webtoons",
    "h5.mangatoon.mobi",
    "tienycomic.xyz",
    "truyenqq.com",
    "saytruyen.net",
    // "beeng.net",
    "wcomic",
    "vlogtruyen",
    "cmanga",
    "manhuarock",
    "aquamanga"
];
// 19